const trainer=document.querySelector('#trainer');const stepLabel=document.querySelector('#stepLabel');const progressDots=document.querySelector('#progressDots');
const base=[
{id:'shape-r',type:'choice',eyebrow:'KUJUND',title:'Mis kujund see on?',shape:'rect',options:['RISTKÜLIK','RUUT'],answer:'RISTKÜLIK'},
{id:'intro-p-r',type:'introP',eyebrow:'UUS MÕISTE',title:'Vaata kujundi kogu serva.',shape:'rect'},
{id:'shape-s',type:'choice',eyebrow:'KUJUND',title:'Mis kujund see on?',shape:'square',options:['RISTKÜLIK','RUUT'],answer:'RUUT'},
{id:'intro-p-s',type:'introP',eyebrow:'UUS MÕISTE',title:'Ka ruudul on ümbermõõt.',shape:'square'},
{id:'pick-p',type:'choice',eyebrow:'ERISTA',title:'Mis on esile tõstetud?',shape:'square',visual:'outline',options:['P · ÜMBERMÕÕT','S · PINDALA'],answer:'P · ÜMBERMÕÕT'},
{id:'intro-s-r',type:'introS',eyebrow:'UUS MÕISTE',title:'Vaata kujundi kogu sisepinda.',shape:'rect'},
{id:'shape-r2',type:'choice',eyebrow:'KUJUND',title:'Mis kujund see on?',shape:'rectTall',options:['RISTKÜLIK','RUUT'],answer:'RISTKÜLIK'},
{id:'intro-s-s',type:'introS',eyebrow:'UUS MÕISTE',title:'Ka ruudul on pindala.',shape:'square'},
{id:'pick-s',type:'choice',eyebrow:'ERISTA',title:'Mis on esile tõstetud?',shape:'rect',visual:'area',options:['P · ÜMBERMÕÕT','S · PINDALA'],answer:'S · PINDALA'},
{id:'four-p',type:'choice4',eyebrow:'ÜHENDA',title:'Vali õige vastus.',shape:'square',visual:'outline',options:['RISTKÜLIK · ÜMBERMÕÕT','RUUT · ÜMBERMÕÕT','RISTKÜLIK · PINDALA','RUUT · PINDALA'],answer:'RUUT · ÜMBERMÕÕT'},
{id:'four-s',type:'choice4',eyebrow:'ÜHENDA',title:'Vali õige vastus.',shape:'rect',visual:'area',options:['RISTKÜLIK · ÜMBERMÕÕT','RUUT · ÜMBERMÕÕT','RISTKÜLIK · PINDALA','RUUT · PINDALA'],answer:'RISTKÜLIK · PINDALA'}];
let queue=base.map(x=>({...x}));let index=0;let locked=false;
function dims(shape){if(shape==='square')return{x:180,y:45,w:220,h:220};if(shape==='rectTall')return{x:210,y:28,w:170,h:250};return{x:105,y:70,w:390,h:185}}
function figure(task,intro=''){const q=dims(task.shape);const cls=intro==='P'?'intro-screen':intro==='S'?'intro-screen intro-area':'';const outline=task.visual==='outline'||intro==='P';const area=task.visual==='area'||intro==='S';return `<div class="figure-stage ${cls}"><svg class="shape-svg" viewBox="0 0 600 320" aria-hidden="true"><rect class="shape-base" x="${q.x}" y="${q.y}" width="${q.w}" height="${q.h}" rx="8"/>${area?`<rect class="shape-area" x="${q.x+7}" y="${q.y+7}" width="${q.w-14}" height="${q.h-14}" rx="4"/>`:''}${outline?`<rect class="shape-outline" x="${q.x}" y="${q.y}" width="${q.w}" height="${q.h}" rx="8"/>`:''}</svg>${intro?`<span class="symbol">${intro}</span><span class="term">${intro==='P'?'ÜMBERMÕÕT':'PINDALA'}</span>`:''}</div>`}
function dots(){progressDots.className='progress-dots';progressDots.innerHTML=base.map((_,i)=>`<i class="${i<Math.min(index,base.length)?'done':''}"></i>`).join('')}
function render(){locked=false;dots();if(index>=queue.length){done();return}const t=queue[index];stepLabel.textContent=`${Math.min(index+1,base.length)}. SAMM`;if(t.type==='introP'||t.type==='introS'){const p=t.type==='introP'?'P':'S';trainer.innerHTML=`<div class="screen"><div class="eyebrow">${t.eyebrow}</div><h1>${t.title}</h1>${figure(t,p)}<button class="single-action" id="confirm">${p} · ${p==='P'?'ÜMBERMÕÕT':'PINDALA'}</button></div>`;document.querySelector('#confirm').onclick=next;return}const four=t.type==='choice4'?' four':'';trainer.innerHTML=`<div class="screen"><div class="eyebrow">${t.eyebrow}</div><h1>${t.title}</h1>${figure(t)}<div class="choices${four}">${t.options.map(o=>`<button class="choice" data-value="${o}">${o}</button>`).join('')}</div><div class="feedback-mark" id="mark"></div></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(b,t))}
function answer(btn,t){if(locked)return;locked=true;const buttons=[...document.querySelectorAll('.choice')];buttons.forEach(b=>b.disabled=true);const ok=btn.dataset.value===t.answer;const correct=buttons.find(b=>b.dataset.value===t.answer);if(ok){btn.classList.add('correct');mark('✓','ok');setTimeout(next,850)}else{btn.classList.add('wrong');if(correct)correct.classList.add('correct');mark('✓','ok');const retry={...t,id:t.id+'-retry-'+index};queue.splice(Math.min(index+4,queue.length),0,retry);setTimeout(next,1250)}}
function mark(s,c){const m=document.querySelector('#mark');m.textContent=s;m.className='feedback-mark '+c}
function next(){index++;render()}
function restart(){queue=base.map(x=>({...x}));index=0;render()}
function done(){stepLabel.textContent='VALMIS';dots();trainer.innerHTML=`<div class="screen"><img class="done-cat" src="../korrutamine-test/assets/edukass-cat-reward-joy.png" alt="EDUKASS"><div class="eyebrow">PROTOTÜÜBI LÕPP</div><h1>Ümbermõõt ja pindala on eristatavad.</h1><p>See prototüüp näitab mõistete visuaalset sissejuhatust, neutraalset veaparandust ja hilisemat tagasipöördumist eksitud oskuse juurde.</p><div class="done-actions"><button id="again">ALUSTA UUESTI</button><a href="../../materials/umbermoot-pindala/">TAGASI MATERJALI JUURDE</a></div></div>`;document.querySelector('#again').onclick=restart}
render();