(()=>{
const DATA={
  et:{
    label:"Eesti",langName:"eesti keel",locale:"et",current:[
      {word:"veekogu",ru:"водоём",chunks:["vee","ko","gu"],fake:["maa","li"]},
      {word:"uurimisobjekt",ru:"объект исследования",chunks:["uu","ri","mis","ob","jekt"],fake:["la","gi"]},
      {word:"mõiste",ru:"понятие",chunks:["mõis","te"],fake:["ma","lik"]},
      {word:"magevesi",ru:"пресная вода",chunks:["ma","ge","ve","si"],fake:["ko","la"]},
      {word:"jõgi",ru:"река",chunks:["jõ","gi"],fake:["ma","nu"]},
      {word:"jõesäng",ru:"русло реки",chunks:["jõe","säng"],fake:["tee","la"]},
      {word:"jõelähe",ru:"исток реки",chunks:["jõe","lä","he"],fake:["su","ma"]},
      {word:"jõesuue",ru:"устье реки",chunks:["jõe","suu","e"],fake:["lä","ma"]},
      {word:"lisajõgi",ru:"приток",chunks:["li","sa","jõ","gi"],fake:["ma","te"]}
    ],
    archive:[{title:"Набор 1",words:[
      {word:"tee kokkuvõte",ru:"подведи итог",chunks:["tee ","kok","ku","võ","te"],fake:["la","mi"]},
      {word:"lugeja",ru:"читатель",chunks:["lu","ge","ja"],fake:["va","si"]},
      {word:"minu meelest",ru:"по-моему",chunks:["mi","nu ","mee","lest"],fake:["va","ta"]},
      {word:"mõnus",ru:"приятный",chunks:["mõ","nus"],fake:["ka","li"]},
      {word:"toovad vanemad",ru:"родители приносят",chunks:["too","vad ","va","ne","mad"],fake:["si","ku"]},
      {word:"soovitama",ru:"рекомендовать",chunks:["soo","vi","ta","ma"],fake:["le","ga"]},
      {word:"meelt lahutama",ru:"развлекаться",chunks:["meelt ","la","hu","ta","ma"],fake:["si","ko"]},
      {word:"paremini aru saama",ru:"лучше понимать",chunks:["pa","re","mi","ni ","a","ru ","saa","ma"],fake:["ve","lo"]},
      {word:"enamasti",ru:"в основном",chunks:["e","na","mas","ti"],fake:["lu","va"]},
      {word:"valima",ru:"выбирать",chunks:["va","li","ma"],fake:["ga","si"]}
    ]}]
  },
  de:{label:"Deutsch",langName:"saksa keel",locale:"de",current:[],archive:[]}
};
const card=document.getElementById("card"),pill=document.getElementById("pill"),counter=document.getElementById("counter"),progress=document.getElementById("progress"),restart=document.getElementById("restart"),reviewBtn=document.getElementById("reviewBtn"),chestBtn=document.getElementById("chestBtn"),sub=document.getElementById("sub"),tabEt=document.getElementById("tabEt"),tabDe=document.getElementById("tabDe"),ps=[1,2,3,4,5].map(n=>document.getElementById("p"+n));
let lang="et",stage=1,words=[],queue=[],index=0,locked=false,mastered=new Set(),mode="trainer",reviewQueue=[],reviewIndex=0,reviewGood=0,reviewBad=0,reviewFlipped=false,sourceSet="current";
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const norm=s=>s.toLocaleLowerCase(DATA[lang].locale).trim().replace(/[.!?,;:]+$/g,"").replace(/\s+/g," ");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
const vis=s=>s.trim();
document.addEventListener("copy",e=>e.preventDefault());document.addEventListener("cut",e=>e.preventDefault());document.addEventListener("contextmenu",e=>e.preventDefault());
function activeCurrent(){return DATA[lang].current}
function setLanguage(next){lang=next;tabEt.classList.toggle("active",lang==="et");tabDe.classList.toggle("active",lang==="de");sourceSet="current";mode="trainer";words=activeCurrent();if(!words.length){renderEmpty();return}start(1,words)}
function updateSub(){const n=activeCurrent().length;sub.textContent=`${n} ${n===1?"слово":"слов"} · ${DATA[lang].langName}`}
function chrome(){const names={1:"Tutvu",2:"Vali",3:"Koosta",4:"Koosta +",5:"Kirjuta"};pill.textContent=`${stage} / 5 · ${names[stage]}`;ps.forEach((p,i)=>p.classList.toggle("on",i<stage));const total=words.length;counter.textContent=stage===1?`${Math.min(index+1,total)} / ${total}`:`${Math.min(mastered.size+1,total)} / ${total}`;updateSub()}
function start(n,set=words){mode="trainer";progress.hidden=false;restart.hidden=false;restart.textContent=sourceSet==="current"?"↻ Alusta uuesti":"← Сундук";stage=n;words=set;queue=n===1?[...words]:shuffle(words);index=0;locked=false;mastered=new Set();chrome();render()}
function next(){index++;locked=false;if(index<queue.length){chrome();render();return}stage<5?start(stage+1,words):finish()}
function good(item,ms){if(stage>1)mastered.add(item.word);setTimeout(next,ms)}
function defer(item,ms){mastered.delete(item.word);if(index>=queue.length-1){const alt=shuffle(words.filter(w=>w.word!==item.word))[0];if(alt)queue.push(alt)}queue.push(item);setTimeout(()=>{index++;locked=false;chrome();render()},ms)}
function render(){const item=queue[index];if(stage===1)study(item);else if(stage===2)choice(item);else if(stage===3)build(item,false);else if(stage===4)build(item,true);else type(item)}
function study(item){card.innerHTML=`<div class="prompt">${esc(item.word)}</div><div class="translation">${esc(item.ru)}</div><button class="primary" id="next">Edasi →</button>`;card.querySelector("#next").onclick=next}
function choice(item){const opts=shuffle([item,...shuffle(words.filter(w=>w.word!==item.word)).slice(0,3)]);card.innerHTML=`<div class="prompt">${esc(item.ru)}</div><div class="choices" id="choices"></div><div class="feedback" id="fb"></div>`;const box=card.querySelector("#choices");opts.forEach(o=>{const b=document.createElement("button");b.className="choice";b.textContent=o.word;b.onclick=()=>checkChoice(b,o.word===item.word,item,box);box.appendChild(b)})}
function checkChoice(btn,ok,item,box){if(locked)return;locked=true;[...box.children].forEach(b=>b.disabled=true);const fb=card.querySelector("#fb");if(ok){btn.classList.add("correct");fb.className="feedback ok";fb.textContent="✓ Õige!";good(item,850);return}btn.classList.add("wrong");const right=[...box.children].find(b=>b.textContent===item.word);if(right)right.classList.add("correct");fb.className="feedback bad";fb.innerHTML=`<strong style="color:#167047">${esc(item.word)}</strong>`;defer(item,2500)}
function panel(item){return `<div class="panel"><div class="panel-label">Õige vastus</div><div class="panel-bricks">${item.chunks.map(c=>`<span>${esc(vis(c))}</span>`).join("")}</div><div class="panel-word">${esc(item.word)}</div></div>`}
function build(item,fakes){const pieces=shuffle([...item.chunks.map((v,i)=>({id:"c"+i,v})),...(fakes?item.fake.map((v,i)=>({id:"f"+i,v})):[])]),selected=[];card.innerHTML=`<div class="prompt">${esc(item.ru)}</div><div class="build-zone" id="zone"><span class="placeholder">Собери здесь</span></div><div class="built" id="built"></div><div class="bank" id="bank"></div><div class="build-actions"><button class="secondary" id="clear">Очистить</button><button class="primary" id="check">Kontrolli</button></div><div class="feedback" id="fb"></div><div id="host"></div>`;const zone=card.querySelector("#zone"),bank=card.querySelector("#bank"),built=card.querySelector("#built"),check=card.querySelector("#check"),clear=card.querySelector("#clear");
function redraw(){zone.innerHTML="";if(!selected.length){zone.classList.remove("has");zone.innerHTML='<span class="placeholder">Собери здесь</span>'}else{zone.classList.add("has");selected.forEach(p=>{const b=document.createElement("button");b.className="brick";b.textContent=vis(p.v);b.onclick=()=>{if(locked)return;selected.splice(selected.findIndex(x=>x.id===p.id),1);const src=bank.querySelector(`[data-id="${p.id}"]`);if(src){src.disabled=false;src.classList.remove("used")}redraw()};zone.appendChild(b)})}built.textContent=selected.map(x=>x.v).join("").trim()}
pieces.forEach(p=>{const b=document.createElement("button");b.className="brick";b.dataset.id=p.id;b.textContent=vis(p.v);b.onclick=()=>{if(locked||b.disabled)return;selected.push(p);b.disabled=true;b.classList.add("used");redraw()};bank.appendChild(b)});clear.onclick=()=>{if(locked)return;selected.length=0;[...bank.children].forEach(b=>{b.disabled=false;b.classList.remove("used")});redraw()};check.onclick=()=>checkBuild(item,selected,zone,bank,check,clear)}
function checkBuild(item,selected,zone,bank,check,clear){if(locked)return;const fb=card.querySelector("#fb");if(!selected.length)return;locked=true;check.disabled=clear.disabled=true;[...bank.children].forEach(b=>b.disabled=true);const ok=norm(selected.map(x=>x.v).join(""))===norm(item.word),ans=[...zone.querySelectorAll(".brick")];if(ok){ans.forEach(b=>b.classList.add("green"));fb.className="feedback ok";fb.textContent="✓ Õige!";card.querySelector("#host").innerHTML=panel(item);good(item,1250);return}ans.forEach(b=>b.classList.add("red"));card.querySelector("#host").innerHTML=panel(item);defer(item,3800)}
function type(item){card.innerHTML=`<div class="prompt">${esc(item.ru)}</div><form class="input-row" id="form"><input id="answer" autocomplete="off" autocapitalize="none" spellcheck="false"><button class="primary">Kontrolli</button></form><div class="feedback" id="fb"></div><div id="host"></div>`;const form=card.querySelector("#form"),input=card.querySelector("#answer");["paste","drop"].forEach(t=>input.addEventListener(t,e=>e.preventDefault()));input.addEventListener("beforeinput",e=>{if(["insertFromPaste","insertFromDrop","insertFromYank"].includes(e.inputType))e.preventDefault()});input.addEventListener("keydown",e=>{if(((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="v")||(e.shiftKey&&e.key==="Insert"))e.preventDefault()});input.focus();form.onsubmit=e=>{e.preventDefault();if(locked||!input.value.trim())return;locked=true;const ok=norm(input.value)===norm(item.word);input.disabled=true;form.querySelector("button").disabled=true;if(ok){input.classList.add("correct");card.querySelector("#fb").className="feedback ok";card.querySelector("#fb").textContent="✓ Õige!";good(item,900)}else{input.classList.add("wrong");card.querySelector("#host").innerHTML=panel(item);defer(item,3500)}}}
function startReview(set=activeCurrent(),back="trainer"){if(!set.length){renderEmpty();return}mode="review";sourceSet=back;words=set;reviewQueue=shuffle(set);reviewIndex=0;reviewGood=0;reviewBad=0;reviewFlipped=false;progress.hidden=true;pill.textContent=`🃏 ${set.length}`;restart.hidden=false;restart.textContent=back==="chest"?"← Сундук":"← Treener";renderReview()}
function renderReview(){if(reviewIndex>=reviewQueue.length)return finishReview();reviewFlipped=false;const item=reviewQueue[reviewIndex],left=reviewQueue.length-reviewIndex;counter.textContent=`${left} осталось`;pill.textContent=`🃏 ${left}`;card.innerHTML=`<div class="review-wrap"><div class="flashcard" id="flash"><div class="flashcard-inner"><div class="flash-face flash-front">${esc(item.ru)}</div><div class="flash-face flash-back">${esc(item.word)}</div></div></div><div class="review-actions" id="reviewActions" hidden><button class="review-no" id="reviewNo">✕</button><button class="review-yes" id="reviewYes">✓</button></div><div class="review-stats"><span>✓ ${reviewGood}</span><span>✕ ${reviewBad}</span></div></div>`;const flash=card.querySelector("#flash"),actions=card.querySelector("#reviewActions");let x0=null;flash.onclick=()=>{if(reviewFlipped)return;reviewFlipped=true;flash.classList.add("flipped");actions.hidden=false};flash.addEventListener("pointerdown",e=>{x0=e.clientX});flash.addEventListener("pointerup",e=>{if(!reviewFlipped||x0===null)return;const dx=e.clientX-x0;x0=null;if(Math.abs(dx)>70)classifyReview(dx>0)});card.querySelector("#reviewNo").onclick=()=>classifyReview(false);card.querySelector("#reviewYes").onclick=()=>classifyReview(true)}
function classifyReview(ok){if(!reviewFlipped||locked)return;locked=true;const flash=card.querySelector("#flash");flash.classList.add(ok?"fly-right":"fly-left");if(ok){reviewGood++;setTimeout(()=>{reviewIndex++;locked=false;renderReview()},260);return}reviewBad++;setTimeout(()=>{const [missed]=reviewQueue.splice(reviewIndex,1);const remaining=reviewQueue.length-reviewIndex;if(remaining>0){const minPos=Math.min(reviewIndex+1,reviewQueue.length);const pos=minPos+Math.floor(Math.random()*(reviewQueue.length-minPos+1));reviewQueue.splice(pos,0,missed)}else{reviewQueue.splice(reviewIndex,0,missed)}locked=false;renderReview()},260)}
function finishReview(){counter.textContent="";pill.textContent="🃏 0";card.innerHTML=`<div class="done"><div class="big">🃏</div><h2>Valmis!</h2><div class="review-stats" style="justify-content:center;margin-bottom:20px"><span>✓ ${reviewGood}</span><span>✕ ${reviewBad}</span></div><button class="primary" id="reviewAgain">Veel kord</button></div>`;card.querySelector("#reviewAgain").onclick=()=>startReview(words,sourceSet)}
function finish(){counter.textContent="";pill.textContent="Valmis";ps.forEach(p=>p.classList.add("on"));card.innerHTML='<div class="done"><div class="big">🌿</div><h2>Kõik tehtud!</h2><button class="primary" id="again">Tee veel üks ring</button></div>';card.querySelector("#again").onclick=()=>start(1,words)}
function renderEmpty(){mode="empty";words=[];updateSub();progress.hidden=true;counter.textContent="";pill.textContent=DATA[lang].label;restart.hidden=true;card.innerHTML=`<div class="empty"><div class="big">🇩🇪</div><h2>Deutsch</h2><p>Немецкая вкладка готова. Здесь появится такой же тренажёр, когда добавим первый набор немецких слов.</p></div>`}
function openChest(){mode="chest";progress.hidden=true;counter.textContent="";pill.textContent="🧰 Сундук";restart.hidden=false;restart.textContent="← Актуальные";const sets=DATA[lang].archive;if(!sets.length){card.innerHTML='<div class="empty"><div class="big">🧰</div><h2>Сундук пока пуст</h2><p>Старые наборы будут появляться здесь после замены актуальных слов.</p></div>';return}card.innerHTML=`<div><div class="chest-title">🧰 Сундук</div><p class="chest-note">Старые слова остаются здесь для повторения.</p><div class="archive-list">${sets.map((s,i)=>`<div class="archive-item"><div class="archive-head"><strong>${esc(s.title)}</strong><span>${s.words.length} слов</span></div><div class="archive-words">${s.words.map(w=>esc(w.word)).join(" · ")}</div><div class="archive-actions"><button class="secondary" data-cards="${i}">🃏 Карточки</button><button class="primary" data-train="${i}">5 этапов</button></div></div>`).join("")}</div></div>`;card.querySelectorAll("[data-cards]").forEach(b=>b.onclick=()=>startReview(sets[Number(b.dataset.cards)].words,"chest"));card.querySelectorAll("[data-train]").forEach(b=>b.onclick=()=>{sourceSet="chest";words=sets[Number(b.dataset.train)].words;start(1,words)})}
reviewBtn.onclick=()=>startReview(activeCurrent(),"trainer");chestBtn.onclick=openChest;tabEt.onclick=()=>setLanguage("et");tabDe.onclick=()=>setLanguage("de");restart.onclick=()=>{if(mode==="chest"||sourceSet==="chest"){sourceSet="current";openChest();return}if(mode==="review"||mode==="trainer"){sourceSet="current";words=activeCurrent();start(1,words)}};setLanguage("et");
})();